"""
Generated schemas for user.py

This file is auto-generated by Norma CLI.
Do not modify manually.
"""

# TODO: Implement actual schema generation
# from norma.schema import generate_schemas
# from models.user import *

# Generated schemas would be here
